### PR TITLE
Fix sharing example: bitbucket links to GitHub

### PR DESCRIPTION
**Pull request by mhansen**
Links were dead because bitbucket dropped mercurial support.

### CODE REVIEW

**Comment by xuhcc** [comment]
Hi @mhansen !

This markdown document is generated automatically by parsing the Google document: https://docs.google.com/document/d/1FRcJqUfeAMQO6KjG94w6rF7VajMGJaFplmF1Wu0rCHY/edit

The Google Docs remain the main place for beancount documentation, so any edits should happen there. 

---

@blais, please take a look. Could you update links in the Google doc according to this PR?

**Comment by mhansen** [comment]
Oh wow. Neat architecture! Benefits of both version control and easy
editing.

**Comment by blais** [comment]
Yeah... it's all over unfortunately. I think ideally we'd write a script against the Google Docs API to at least find all the instances of such links. I should count them, see if it makes more sense to fix them manually.

**Comment by blais** [comment]
Hmmm 92
Borderline

**Comment by blais** [comment]
I made a list by grepping through the extraction from Kirill, I'll fix them manually.

**Comment by xuhcc** [comment]
Thanks Martin!

The markdown documents has been updated.

**Comment by blais** [comment]
There's a bunch more TBD BTW, I'll do it little by little.

Another thing I'd like to review at some point is to make sure all the docs
are converted to your markdown format. There may be a few missing, I'm not
even sure what the full list is anymore, I have them all in a Drive folder.
I've been meaning to review this.

**Comment by blais** [comment]
https://github.com/beancount/beancount/issues/551

**Comment by xuhcc** [comment]
>Another thing I'd like to review at some point is to make sure all the docs
are converted to your markdown format. There may be a few missing,

The parser gets all documents from the index: https://docs.google.com/document/d/1RaondTJCS_IUPBHFNdT8oqFKJjVJDsfsn6JEjBG04eA

Here's the latest addition, for example: https://beancount.github.io/docs/calculating_portolio_returns.html

**Comment by blais** [comment]
Ohhh... okay. I'm still reviewing that code heavily, haven't sent a link to
the returns doc on the list.
Cool

**Pull request closed without merging**
